name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - run: yarn install --frozen-lockfile
      # Deal with OOM https://github.com/vitejs/vite/issues/2433
      - run: NODE_OPTIONS="--max-old-space-size=8192" yarn build
